# Generated by Django 3.2.7 on 2021-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210927_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplodedpic',
            name='fb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uplodedpic',
            name='insta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uplodedpic',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
