# Generated by Django 3.2.7 on 2021-09-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210928_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uplodedpic',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='uplodedpic',
            name='fb',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
